image: python:3.9-buster

stages:
  - style
  - build
  - test
  - deploy

# style
flake8:
  stage: style
  script:
    - pip install --upgrade flake8==5
    - flake8 --exclude=_version.py rtctools_diagnostics --max-line-length 99
  tags:
    - docker

build:
  stage: build
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  tags:
    - docker

unittest:
  stage: test
  script:
    - pip install tox
    - tox -vv

deploy:
  stage: deploy
  dependencies:
    - build
  script:
      - pip install -U twine
      - twine upload -u $PYPI_USER -p $PYPI_PASSWORD dist/*
  only:
      - tags
