image: python:3.9-buster

stages:
  - style

# style
flake8:
  stage: style
  script:
    - pip install --upgrade flake8==5
    - flake8 --exclude=_version.py rtctools_diagnostics --max-line-length 99
  tags:
    - docker
